DATAS SEGMENT
      STRING1 DB 'PERSONA$'
DATAS ENDS
EXT SEGMENT
STRING2 DB 'PERSINB$'
EXT ENDS
CODES SEGMENT
   ASSUME CS:CODES,DS:DATAS,ES:EXT
START:
   MOV AX,DATAS
   MOV DS,AX
   MOV AX,EXT
   MOV ES,AX
   ; READ A STRING
   ; CMP
   ; NOTE : CMP ES:DI - DS:SI UNILL CX=0 OR ZF=0
   LEA DI,STRING1
   LEA SI,STRING2
   MOV CX,14
   CLD
    REPE CMPSB
    ; OUTPUT DIFFERENCE
    MOV DL,0AH
    MOV AH,02H
    INT 21H
DEC SI
    MOV DL,DS:[SI]
    MOV AH,02H
    INT 21H
   ; END
   MOV AH,4CH
   INT 21H
CODES ENDS
   END START
